##
# This file is part of the ChillDev-Lambda.
#
# @license http://mit-license.org/ The MIT license
# @copyright 2018 © by Rafal Wrzeszcz - Wrzasq.pl.
##

#FIXME: https://github.com/travis-ci/travis-ci/issues/753

language: "java"

sudo: false

dist: "trusty"

branches:
    except:
        - "/^release-/"

jdk:
    - "openjdk8"
    - "oraclejdk8"
    - "oraclejdk9"
    - "openjdk10"
    - "openjdk11"
    - "oraclejdk11"

# TODO: temporary as delombok won't work here
matrix:
    allow_failures:
        -
            jdk: "openjdk11"
        -
            jdk: "oraclejdk11"

env:
    global:
        - "AWS_REGION=eu-central-1"
        -
            secure: |-
                j57Rp7c2gD1tvDJygi4AseV0WdhRRciWrNtxrztq+DMPxKzXYlsIxaZOEiUBSV8JlLYQ81rqln82y+z+5Mcb/9zFQ6Xn53+bMe3/+i3
                E9WkK9asNYk13uNHUOZvQjLWwYuXob6ubs19l+JYnzczYb7w7T3TefLmv1X9/bRPgahJJwabwj2y4YGgsDuqLl7qZ/dgruzGLuoalH8
                Dl2JI4Kc7Krjp+9XMC9almCieif2KDnvI7QYXlBzG9yhTdpctyWmNRytNbebthWe0cSg0qX4fSg3/sYi3Z8W1S7RJ3nrshqtP9JTEKb
                +w3FsVomM0MeFKQW7WeEBswQ6sAwwDKk9ttQOXgX5t8EivLbYS2uY5yNJL94R/JsBeB2NYddCvXg3lrZFzprYgI0bTJU/GOzMAUfwJ1
                jabUYZLFnyFyIBFMg0D5siGUe848O968TPmbIzze++VWnH3w9A/ahYfbZOkfWUSLuqTJIV7LF0/lb841mjtwMf19cQiODbzbrpz8n1R
                g073SGAmkVCLQNopVAVKP7UTUIGqH9kJlhOXuNcvwuWUjaStEzlNLeeO+FkK7NOfaFHibc401s5a6wc54DBeQk6LcIYBPC02YO9thRX
                1dWsO/ipfR1TJilSRYxiCUyfrqPBp4SsyoMLha9MBtQBAaWe8Gt7+yAv2x0oI3gY0=
        -
            secure: |-
                NbbiZg8vcKpRbfjhnqAl4TZHlYztXTh5YGwaJ08ChzTlNZoWvGTvUNiseOH2RcFjEgTVfUtLNkeZ2elrVJsUnQMLg+hRokc86UD1OSj
                CvRdS0Jde2qzqwTeHPuHr0DIV8qFbrxVQwgoZbBO6mw5+I4u10yrIjsVJh6MLg3f18quBcNWYtkLTLvNzb9zGRiyySUVvdVFjGh+Wt6
                dr/fV2RO6sxnHQB646jKTshaehxqWO09V72HVx+1+H2P2lzmSWqWLud0B7ktDNa2FmUWlLP4watI66rV3N8eRswYTQHlivW2paNE9uY
                nRGsYVDq3P1+UdFfBGz3QjfVko3erV65AxT9MvNzR7yUy1xZB57D/3+efjXBEh4qcG2Ynb62G76LvAkl+ae0OSKE2hRGepLy3YC5Jui
                g+GP6i5PUwkSWe+Lzvy/HXiTVbtdu4XKM8ptQLjBHefPapc9JE7KEhrpJH1+YsdZBJID7P+iXXv+iLnT1x/93FnY5voGdwb37GNzOyH
                xiKifwljWMDXAqXbwe6R9QFd7l+dvgfa5tq5XChH9TTg/KwYsXKM3Me6ci1ag2Zv40dA5635Yq8W5sCZ3fAAN+KseEZQuecjHbqYoM4
                AwRnCOAWJX8FkZAaDPW9GsBRBOjh/EfguBXd+SAENzxLTv3axDLmZsES8eRC7JSUc=
        -
            secure: |-
                clm7klbHFEsA0W6I+r85rJ0KaS2Quy6uKRaN9Vrq5qkcPcvWUUZwizX7Bz7/OnL3GzYZPZNsrY34enuSG0wCejo9MgwBY21JMeu33uX
                M9TtEZWRyToohXvzB19jFtF0vqSPJnwnFgBjDidOg6IfIGzSqlTX+U8vpNvTN5KV6Yy8wwZtdo63p7qtg92OVDEPoOy2wxBojsHclQp
                mNjluO1zFPzkVKYY9/yw6ds2HEJDTUdAKlGQgeL/0yVjCc50UryWVZozYiYXSNIhdWUH4lCd02YJ7HMJtncZoQZ0v6PQMEBuQ3YlJgD
                F4S2pSEFnpgRYR/Rsa5UxHeIffA3yAcpZFoBPcxKtPtzk4+bjZhE7q7gUti2M7NFhjPouDtWrc6JZ/7Dt/r3kCmhFqYUO+V/uYYo80F
                KgTw+NydPcS3j5qDwt2G+mV4A/tLp1kLkcWVa6djx2xQoB9LSuai7lbUaxz64uUyLbNqvOhulnJQgvE41X1UWdT1Da2Pm+qQfuqoZwi
                W9mMCd2tSOc14k5AyA7Z1l3EdT574VIMongov2DQWE34iAQZs2bFzT0fK9rYtc9c+0ZIciihF8DZaTatJ7LTwaUY6zTvC8o3iwU6tgX
                uY/CU4oEAyrrHFTmtd7iGQQyCyAi8swn8qjOSYTam1PBLpGVWoZapoXQatZqgn80c=
        -
            secure: |-
                jhUmeLYxpkDdgAj7eLPvHGNWl2cf5xOvryW6ydBIBGr+gg3DHOwTQoYPKhRDyNJmhOSpeJsb8TAQHUkucvahvFI5nQulX1P+olzTBvd
                hhPakFdfCgwq5qARQdyo9U63bfmRl56LG14KIuRuzcnLhbJyCFaZfpTOc4SnDEZaaJ8maFKzdlNryzk7Hoit0q3XzaOza7jOXmu0ytL
                8fvyjByA2OF3ffWkV/hlz90SQHFyPp7OPGBLz3V0hZdpZ7RPxyNaAZbqVscWMc3PX77pqg5eS32NStjR/5hsTK3y02ozk523PXSbOI6
                lVl9SLN8MWFY+bzNC7jPCUIU0uIK3FPKwhQwyWmTGbVYznhBlMMrIf3gKg3qExruM1t68iYsa+yuggT5kbar3orE4IxrdvS40iAtmyL
                0lRu1HyVlo6T7xgew0pKhaOeE4f53dM7W/vS+TvVuzR1CXFwZdY6dxSzHuNHHLJC1BHytT6bCnVh1Fh70Bn/iZYG/iI9YevC6os7lwB
                5uWNI9COxbYD8rNO6RCebNFJYIaMrYPDItd7CdG4v+8ImKqxr8z2LLo+pxB8S9mIEMO+AbUNj0b0RJA4SvSoSuwKRzVf2/P0PSCgoYD
                paaBeHCvmUfLdx2KfwrjdveO+ugGLOf9dSUVJ7KdRAK9EV9FVUHaUoUH+Hbe9Uzn4=
        -
            secure: |-
                du1Im9Xzx/lJK/Oa5USieuM/aCmYb4G+Ad1I0Dte4TzR6ld90c0eo6Gsx9A+aIp+DR2xpnYgzLZZ22/jqxz7fdNSWIcTKzjheOR3s53
                JU+iKV7dAZDH2kgrJo0LP54eOZGeCd7RT2no2rlcBW9O0ejfIowBfV591RvMC/6F6cVSMROCeDQDS17wXOPlQXmJybx0UWB/HDDmLTZ
                COzxKzYmYqUvXhasspKV+412D8v7k/RUPrCOnvK2pIX0K97yge7Q3QBwkZLEkwaAQN/7tviFTusn+LeSr9MA6UbeA6mFCaxVli2ye42
                2aRNwzwK3BwnwAfGEAzUjZTFPJ1GcxDuZPnVXrTokJkb3D9ESotPEnFh5aWe8YhzVGJkNuFniqdwUvJlJaTsFO/z4oKvNNGFY7DJ/Uw
                cddVNM2Y+FU4garSPTYBeD48IcP0kImM7qbM9DYUrIC90k/QvvxGfODGg9usIdqGd989P4RwpZD1BWWVXWK4Zg5WAQriChyYQMJrywA
                QGrcTe5caV2ij/ApusWSZtVt67wrOFXEeHZi2/2HoUKHz2DkKQTiQR5YB187aC1bSSo9JOfhKJUkmJng+FFo01VzWAI/Yj/EnI52C4S
                ImNyftghjBIxJrMO+o46EF7kKe3dYCTL0jGW2g3fh/Mit7NEomWXigFgSbDVuFoRM=

# this is not a boolean, this is a Linux `true` command to simply override this step
install: "true"

script: "mvn -e verify site"

after_script: "mvn -e coveralls:report"

before_deploy:
    - "eval \"$(ssh-agent -s)\""
    - "git config user.name \"Travis CI\""
    - "git config user.email \"office@chilldev.pl\""
    - "openssl aes-256-cbc -k \"${SECRET}\" -in .travis/gpg_key.enc -out .travis/gpg_key -d"
    - "openssl aes-256-cbc -k \"${SECRET}\" -in .travis/id_rsa.enc -out .travis/id_rsa -d"
    # this is needed to avoid duplicated key error as we have two deploys on `master`
    - "rm -f ~/.gnupg/*.gpg"
    - "gpg --fast-import .travis/gpg_key"
    - "chmod 600 .travis/id_rsa"
    - "ssh-add .travis/id_rsa"
    - "echo -e \"Host github.com\\n    StrictHostKeyChecking no\\n\" >> ~/.ssh/config"

deploy:
    -
        provider: "script"
        skip_cleanup: true
        # unfortunately deploy script must be single command
        script: "./.travis/release.sh"
        on:
            branch: "develop"
            condition: "${TRAVIS_EVENT_TYPE} == push"
            jdk: "oraclejdk8"
    -
        provider: "script"
        skip_cleanup: true
        script: "mvn -e deploy site-deploy -P deploy --settings .travis/settings.xml"
        on:
            branch: "master"
            jdk: "oraclejdk8"
    -
        provider: "releases"
        skip_cleanup: true
        api_key: "${GITHUB_TOKEN}"
        file_glob: true
        file: "*/target/*.jar"
        on:
            branch: "master"
            jdk: "oraclejdk8"

cache:
    directories:
        - "${HOME}/.m2/"

before_cache: "rm -rf ${HOME}/.m2/repository/pl/chilldev/lambda"

notifications:
    webhooks:
        urls:
            - "https://webhooks.gitter.im/e/27be3b24be63d41f7b18"
